# Generated by Django 5.1.4 on 2025-01-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
