# Generated by Django 5.1.4 on 2025-01-11 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='state',
            new_name='is_active',
        ),
    ]
